name: Dependency Review

"on":
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

concurrency:
  group: dependency-review-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
