name: Release

"on":
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  actions: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        id: changelog
        run: |
          # Generate changelog from conventional commits
          if command -v npx &> /dev/null; then
            npx conventional-changelog-cli -p conventionalcommits -i CHANGELOG.md -s -r 0
            echo "changelog_content<<EOF" >> $GITHUB_OUTPUT
            cat CHANGELOG.md >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            # Fallback to simple git log
            echo "changelog_content<<EOF" >> $GITHUB_OUTPUT
            echo "## Changes" >> $GITHUB_OUTPUT
            git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")..HEAD >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: ncipollo/release-action@v1.16.0
        with:
          body: ${{ steps.changelog.outputs.changelog_content }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release ${{ steps.version.outputs.version }}"
          tag: ${{ steps.version.outputs.version }}
