name: Release

"on":
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  actions: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install changelog dependencies
        run: |
          npm init -y
          npm install --no-save conventional-changelog-cli

      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        id: changelog
        run: |
          # Generate changelog from conventional commits
          if [ -f "node_modules/.bin/conventional-changelog" ]; then
            ./node_modules/.bin/conventional-changelog -p conventionalcommits -i CHANGELOG.md -s -r 0
            echo "changelog_content<<EOF" >> $GITHUB_OUTPUT
            cat CHANGELOG.md >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            # Fallback to simple git log
            echo "changelog_content<<EOF" >> $GITHUB_OUTPUT
            echo "## Changes" >> $GITHUB_OUTPUT
            git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")..HEAD >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated changelog
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -f "CHANGELOG.md" ] && ! git diff --quiet CHANGELOG.md; then
            git add CHANGELOG.md
            git commit -m "docs: update CHANGELOG.md for ${{ steps.version.outputs.version }} [skip ci]"

            # Push to main branch
            git push origin main

            # Also push to develop branch if it exists
            if git show-ref --verify --quiet refs/remotes/origin/develop; then
              git checkout develop
              git merge main --no-edit
              git push origin develop
              git checkout main
            fi
          else
            echo "No changes to CHANGELOG.md"
          fi

      - name: Create Release
        uses: ncipollo/release-action@v1.16.0
        with:
          body: ${{ steps.changelog.outputs.changelog_content }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release ${{ steps.version.outputs.version }}"
          tag: ${{ steps.version.outputs.version }}
