name: Release
on:
  push:
    tags:
      - "v*.*.*"

# Enforce minimal token permissions by default
permissions:
  contents: write
  actions: read

# Prevent parallel release jobs for the same tag
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Changelog
        id: changelog
        uses: conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: true
          skip-commit: true
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
