name: Semantic PR

"on":
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

concurrency:
  group: semantic-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # List of allowed commit types
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert

          # Configure scope requirements
          requireScope: false
          disallowScopes: |
            release

          # Subject line requirements
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.

          # Additional validations
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: false

          # Header validations
          headerPattern: '^(\w+)(?:\(([^\)]+)\))?: (.+)$'
          headerPatternError: |
            The PR title doesn't match the expected format.
            Expected format: <type>(<scope>): <subject>
            Example: feat(auth): add login functionality
