name: Semantic PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

# Only allow read permissions by default
permissions:
  contents: read

# Run one validation per PR
concurrency:
  group: semantic-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: "The subject \"{subject}\" found in the pull request title \"{title}\"\ndidn't match the configured pattern. Please ensure that the subject\ndoesn't start with an uppercase character. "
